export * from './parentPages/Login'
export * from './Register'
export * from './Choose'
export * from "./SplashScreen"
export * from "./childpages/ChatHomeChild"
export * from './childpages/HomeChild'
export * from './childpages/ChatChild'
export * from './childpages/SosChild'
export * from './childpages/SettingsChild'
export * from './parentPages/HomeParent'
export * from './childpages/ConnectionCode'
export * from './parentPages/Chat'
export * from './parentPages/Voice'
export * from './parentPages/ChildEvents'
export * from './parentPages/Settings'
export * from './parentPages/ChatHome'
export * from './parentPages/ChooseChild'
export * from "./parentPages/PackagePage"
export * from './SwiperPage'
export * from "./parentPages/EditUser"
export * from "./parentPages/EmailVerification"

